version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog_data
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: backend
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: blog_data
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_PORT: 3306
    ports:
      - "8000:8000"
    depends_on:
      - db
    sysctls:
      net.core.somaxconn: 4096
    volumes:
      - .:/app
      - /tmp/app/mysqld:/run/mysqld
