version: '3.7'

services:
  # redis:
  #   image: 'bitnami/redis:latest'
  #   container_name: redis
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   ports:
  #     - 6379:6379

  db:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123qweA@#
      MYSQL_DATABASE: fabbi
      MYSQL_USER: fabbi
      MYSQL_PASSWORD: 123qweA@#
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
    ports: 
      - 8080:80
    depends_on: 
      - db

  backend:
    build:
      context: .
    container_name: backend
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: fabbi
      DATABASE_USER: fabbi
      DATABASE_PASSWORD: 123qweA@#
      REDIS_HOST: redis
    depends_on:
      - redis
      - db
    sysctls:
      net.core.somaxconn: 4096
    volumes:
      - /tmp/sock:/vol/sock
      - /vol/web/static:/vol/web/static
      - /vol/logs:/vol/logs
