[tool.autopep8]
max_line_length = 160
ignore = "E265,E266"  # or ["E265", ...]
in-place = true
recursive = true
aggressive = 2
verbose = true

[tool.coverage.run]
omit = [
    "*/tests/*",
    ".venv/*",
    "venv/*",
    "*/.virtualenvs/*",
    "*/config/*",
]

[tool.isort]
profile = "django"
line_length = 160