# Generated by Django 4.0.1 on 2022-01-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('doing', 'Doing'), ('done', 'Done')], default='not_started', max_length=32),
        ),
    ]
