# Generated by Django 4.1 on 2022-08-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_category_post_tag_rating_productcomment_post_tag_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
