# Generated by Django 4.1 on 2022-08-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="content",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
