# Generated by Django 4.1 on 2022-08-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_tag_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(blank=True, related_name="tags", to="api.tag"),
        ),
    ]
