# Generated by Django 4.1 on 2022-08-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
